# Generated by Django 2.0.6 on 2018-06-30 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='Author',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='article',
            name='Title',
            field=models.CharField(max_length=150),
        ),
    ]
